root = "."
testdata_dir = "testdata"
tmp_dir = "bin"

[build]
  args_bin = []
  bin = "bin\\main.exe"
  # Faster build command with optimizations
  cmd = "go build -ldflags='-s -w' -o ./bin/main.exe ./cmd"
  delay = 100              # Reduced from 1000ms to 100ms
  exclude_dir = [
    "assets", "bin", "vendor", "testdata", 
    "node_modules", ".git", "docs", "scripts"
  ]
  exclude_file = []
  exclude_regex = ["_test.go", ".*_test.go", "\\.git", "\\.tmp"]
  exclude_unchanged = true  # Skip unchanged files
  follow_symlink = false
  full_bin = ""
  include_dir = ["cmd"]     # Only watch specific directories
  include_ext = ["go"]      # Only watch .go files (removed html, tpl, tmpl)
  include_file = []
  kill_delay = "500ms"      # Reduced from 2s to 500ms
  log = "build-errors.log"
  poll = false              # Use file system events (faster than polling)
  poll_interval = 0
  post_cmd = []
  pre_cmd = []
  rerun = false
  rerun_delay = 100         # Reduced from 500ms to 100ms
  send_interrupt = true
  stop_on_error = false

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = true          # Only show main app logs (less noise)
  silent = false
  time = false

[misc]
  clean_on_exit = true

[proxy]
  app_port = 0
  enabled = false
  proxy_port = 0

[screen]
  clear_on_rebuild = true   # Clear screen for better visibility
  keep_scroll = false       # Don't keep scroll for faster refresh